# Cloudflare Pages configuration

[site]
name = "tendas-mozambique"
bucket = "./dist"

[build]
command = "npm run build"
publish = "dist"

# Handle client-side routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
